inputs:
  inputDir: '../datasets/uci_har'
  # Note: 'baseName' is used to form the CSV input file names. 
  # E.g: '<baseName>_train.csv' and '<baseName>_test.csv'
  baseName: 'inertial_signals' 
  metricName: 'body_acc_x'
  metricMin: -0.1
  metricMax: 0.1

outputs:
  outputDir: 'traces'

networkRunner:
  batchSize: 1000
  runSanity: False
