inputs:
  inputDir: '../datasets/SyntheticData/Test1'
  trainFileName: 'Test1_TRAIN'
  testFileName: 'Test1_TEST'
  timeIndexed: False
  metricName: null
  metricMin: 0.0
  metricMax: 1.0

outputs:
  outputDir: 'traces'

params:
  chunkSize: 10
  runSanity: False
