inputs:
  inputDir: 'data'
  # Note: 'baseName' is used to form the CSV input file names. 
  # E.g: '<baseName>_train.csv' and '<baseName>_test.csv'
  base_name: 'synthetic_control' 
  metric_name: 'scalar'
  metricMin: -0.1
  metricMax: 0.1

outputs:
  outputDir: 'traces_ucr'

params:
  batchSize: 1000
  runSanity: False
