inputs:
  inputDir: 'data'
  # Note: 'baseName' is used to form the CSV input file names. 
  # E.g: '<baseName>_train.csv' and '<baseName>_test.csv'
  baseName: 'test1' 
  metricName: 'scalar'
  metricMin: 0.0
  metricMax: 1.0

outputs:
  outputDir: 'traces_motifs'

params:
  batchSize: 1000
  runSanity: False
