inputs:
  input_dir: '../htm/traces'
  train_file_name: 'trace_body_acc_x_TRAIN'
  test_file_name: 'trace_body_acc_x_TEST'
  metric_name: 'sequenceEmbedding'

outputs:
  results_output_dir: 'results'
  model_output_dir: 'model'
  history_file: 'train_history.csv'
  prediction_file: 'predictions.csv'
  model_name: 'baseline.h5'

params:
  chunk_size: 10
  batch_size: 32
  num_epochs: 10
  ma_window: 10
  input_shape: (100, 65536)
  output_dim: 6
  labels: ['WALKING',
          'WALKING_UPSTAIRS',
          'WALKING_DOWNSTAIRS',
          'SITTING',
          'STANDING',
          'LAYING']
  # If lazy=True, don't load all the data in memory and train the model chunk
  # by chunk. Repeat for each epoch. (Memory efficient but slower because 
  # at each epoch, the lazy panda data frame iterator needs to re-created).
  # If lazy=False, load all the data in memory and train the model for 
  # multiple epochs (Memory intensive, but faster - since the panda data 
  # frame is only loaded at the beginning).
  lazy: False
  # If train=True, train a model.
  # If train=False, load a model from disk.
  train: True 
  

